apiVersion: apps/v1
kind: Deployment
metadata:
    name: k8s-test
    labels:
        app: k8s-test
spec:
    replicas: 2
    selector:
        matchLabels:
            app: k8s-test
    template:
        metadata:
            labels:
                app: k8s-test
        spec:
            containers:
                - name: k8s-test
                  image: k8s-test:1.0.0
                  resources:
                      requests:
                          memory: "64Mi"
                          cpu: "250m"
                      limits:
                          memory: "128Mi"
                          cpu: "500m"
                  ports:
                      - containerPort: 8080
                - name: crashy
                  image: busybox
                  resources:
                      requests:
                          memory: "64Mi"
                          cpu: "250m"
                      limits:
                          memory: "128Mi"
                          cpu: "500m"
                  command:
                      [
                          "sh",
                          "-c",
                          "echo 'Simulating crash...'; sleep 5; exit 1",
                      ]
